### ISSUE TITLE
setup.py installs to UNKNOWN-0.0.0

### ISSUE THREAD

**Issue by orbea** [python-xlib/python-xlib#106]
OS: `Slackware64-14.2`
`python-2.7.14-x86_64-1_slack14.2`
`python3-3.6.4-x86_64-1_SBo`

When building and isntalling python-xlib using `setup.py` with either python2 or python3 I found its being installed to paths like this.
```
usr/lib64/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info/
usr/lib64/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info/requires.txt
usr/lib64/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info/PKG-INFO
usr/lib64/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info/top_level.txt
usr/lib64/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info/dependency_links.txt
usr/lib64/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info/SOURCES.txt
```
As a consequence any other python modules that use python-xlib fail to find it.

I bisected this to the following commit.
```
22a8e1929ad58b8168bcf5d931e8f6067ebdec0a is the first bad commit
commit 22a8e1929ad58b8168bcf5d931e8f6067ebdec0a
Author: Benoit Pierre <benoit.pierre@gmail.com>
Date:   Mon Dec 4 17:46:50 2017 +0100

    fixup metadata
    
    - use `setup.cfg`
    - tweak `README.rst`
    - mark Python 3.6 as supported
    - convert `NEWS` to `CHANGELOG.md`
    - set long description to the contents of `README.rst`

:000000 100644 0000000000000000000000000000000000000000 a33f8fdb0da2c2ad8a11c6edf904f2fd48906584 A	CHANGELOG.md
:100644 000000 0483c58fae9d32ad70257841aa201512dd2218f4 0000000000000000000000000000000000000000 D	NEWS
:100644 100644 f145f3da37439f202b8014fdf1a64b6a616a3601 e28f80cf90aa4ae49610a368b3a1164f72c5aeb9 M	README.rst
:100644 100644 2a9acf13daa95e85642ea255d3e3bd1ef8252804 ba1f408a289b95dee0a5f76981d66d94d2beeecf M	setup.cfg
:100644 100644 b425618fc1c48a7d7102a0bde6a1da04ac1d89cc 9b4a47e2d2283996c0248fe066e6abba06c5b6d3 M	setup.py
```
22a8e1929ad58b8168bcf5d931e8f6067ebdec0a

More specifically this started when `setup.cfg` was being used instead of `setup.py`.

I can partially revert this commit to resolve the issues, but a better solution would be preferred.
```
diff --git a/setup.py b/setup.py
index b425618..9b4a47e 100644
--- a/setup.py
+++ b/setup.py
@@ -2,24 +2,10 @@
 
 from setuptools import setup
 
-import Xlib
-
 
 setup(
-    name='python-xlib',
-    version=Xlib.__version_string__,
-
-    description='Python X Library',
-    download_url='https://github.com/python-xlib/python-xlib/releases',
-    url='https://github.com/python-xlib/python-xlib',
-    license='LGPLv2+',
-
-    author='Peter Liljenberg',
-    author_email='petli@ctrl-c.liu.se',
-
     install_requires=['six>=1.10.0'],
     setup_requires=['setuptools-scm'],
-
     packages=[
         'Xlib',
         'Xlib.ext',
@@ -28,22 +14,4 @@
         'Xlib.support',
         'Xlib.xobject'
     ],
-
-    keywords='xlib x11 x windows',
-    classifiers=[
-        'Development Status :: 5 - Production/Stable',
-        'Environment :: X11 Applications',
-        'Intended Audience :: Developers',
-        'License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)',
-        'Operating System :: OS Independent',
-        'Programming Language :: Python :: 2.7',
-        'Programming Language :: Python :: 3',
-        'Programming Language :: Python :: 3.3',
-        'Programming Language :: Python :: 3.4',
-        'Programming Language :: Python :: 3.5',
-        'Programming Language :: Python :: Implementation :: CPython',
-        'Topic :: Software Development :: Libraries :: Python Modules',
-        'Topic :: Software Development :: Libraries',
-        'Topic :: Software Development :: User Interfaces',
-    ],
 )
```
Another thing is that I can not reproduce this issue on Slackware current, but I'm puzzled what the difference is?

**Comment by benoit-pierre** [comment]
It means your version of setuptools is too old.

**Comment by benoit-pierre** [comment]
You need at least 30.3.0.

**Comment by orbea** [comment]
Yes, you are correct!

Slackware 14.2 has `python-setuptools-22.0.5` while Slackware current has `python-setuptools-38.5.1`. So I tried using the newer setuptools from current and the issue is resolved.

However this is problematic because setuptools is unlikely to be updated in a stable Slackware release until 15.0 is out. I think there are three potential ways to work around this and any advice on what is the preferred method is appreciated.

1. Ship python-xlib 0.20 for now.
2. Partially revert that patch as above.
3. python-xlib adds support for older setuptools versions and I apply that future patch to 0.21.

**Comment by benoit-pierre** [comment]
I'm sorry, but I don't think it's unreasonable to expect a reasonably current Python system when building/installing from source. Why not use pip/wheel to install anyway?

**Comment by orbea** [comment]
This is for the slackbuilds.org build script which is currently stuck at `0.14` since the previous maintainer is now inactive for 8 years. Using pip might be fine for individual users, but its not going to work for a repo. :)

**Comment by benoit-pierre** [comment]
If it's for building a distribution package, then you'll have to revert manually by applying a patch locally during building...

**Comment by orbea** [comment]
Understood, until a newer Slackware stable is out I will apply that patch. Thanks for the help!
