### ISSUE TITLE
Bump to v0.24?

### ISSUE THREAD

**Issue by jakogut** [python-xlib/python-xlib#132]
I maintain a package for this module for Buildroot, and my application depends on a change that was made after v0.23. Could we get a new release, so I can bump the Buildroot package?

Thanks!

**Comment by vasily-v-ryabov** [comment]
Sorry for that. I will try to take my time on next weekend to post v0.24 on PyPI.

**Comment by jakogut** [comment]
No need to apologize! Thanks for maintaining this package.

**Comment by vasily-v-ryabov** [comment]
@benoit-pierre has just published v0.24 on PyPI. Closing.
