### ISSUE TITLE
When is the next upstream release scheduled?

### ISSUE THREAD

**Issue by sunweaver** [python-xlib/python-xlib#153]
Hi,

it is good to see active development happen in so short intervals on python-xlib. Thanks for working on this piece of software. Currently, I am preparing an initial upload of GreenWithEnvy [1] by Roberto Leinardi to Debian.

For this to be functional, I need that Roberto's latest contributions to python-xlib end up in Debian unstable. 

 Is there any release date scheduled for python-xlib 0.26? If not, can you schedule one? When could that be?

Once the new upstream release is out, I can coordinate with the recent uploader from Debian's Python Modules Team and coordinate a fresh upstream upload (or even do that my self, as a team-upload).

Thanks!
Mike

**Comment by vasily-v-ryabov** [comment]
Hi @sunweaver release 0.26 is not published on PyPI. Hope it's not too late.

**Comment by sunweaver** [comment]
On  So 08 Dez 2019 13:13:47 CET, Vasily Ryabov wrote:

> Hi @sunweaver release 0.26 is not published on PyPI. Hope it's not too late.

Thanks! Fine by me. My packaging efforts got delayed, too. I will ping  
the Debian maintainer of python-xlib to wrap up the new release as DEB  
package.

Greets,
Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
