### ISSUE TITLE
XTEST fake input API

### ISSUE THREAD

**Issue by matanster** [python-xlib/python-xlib#178]
I'm probably doing something wrong, but unlike [older versions of the API of this library still implied out there](https://chromium.googlesource.com/chromiumos/platform/autox/+/71767d6a38b5c9472752fbc48136105f3d03367b/autox.py), in the latest version, the [`fake_input`](https://github.com/python-xlib/python-xlib/blob/381bc18b012c1f72ccfade063fd50d27afedae89/Xlib/ext/xtest.py#L93) method requires a self argument, implying a slightly contrived usage like the one I implemented below:

```python

from Xlib import X
from Xlib.display import Display
from Xlib.ext import xtest  

class GlobalMouseClickSender(object):

    def __init__(self):
        self.disp = Display()
        self.display = self.disp.display # oddly necessary inside the API method fake_input

    def send_mouse_click(self):
        pointer_data = self.disp.screen().root.query_pointer()
        pprint(pointer_data)

        xtest.fake_input(
            self,
            event_type = X.ButtonPress,
            detail = X.Button1,
            x = pointer_data.root_x, y = pointer_data.root_y)

        xtest.fake_input(
            self,
            event_type = X.ButtonRelease,
            detail = X.Button1,
            x = pointer_data.root_x, y = pointer_data.root_y)

        self.disp.flush()


g = GlobalMouseClickSender()
g.send_mouse_click()
```

Or at least, that's how I wired a `self` object for the function call, one having `self.display` be what `fake_input` expects it to be. 

This works, but I wonder whether there is a simpler way intended.

**Comment by petli** [comment]
The idea with extensions is that they should add methods to the X objects they extend, so it ought to be possible to do this:

```python
self.disp.fake_input(
            event_type = X.ButtonPress,
            detail = X.Button1,
            x = pointer_data.root_x, y = pointer_data.root_y)
```

**Comment by HMaker** [comment]
> The idea with extensions is that they should add methods to the X objects they extend, so it ought to be possible to do this:
> 
> ```python
> self.disp.fake_input(
>             event_type = X.ButtonPress,
>             detail = X.Button1,
>             x = pointer_data.root_x, y = pointer_data.root_y)
> ```

Looks like now he correct is `Display.xtest_fake_input()`, methods are prefixed by extension name.
