### ISSUE TITLE
Error accessing NV-CONTROL

### ISSUE THREAD

**Issue by ga1i13o** [python-xlib/python-xlib#203]
Hi, I have been trying to use Xlib to get info about GPUs, I ran the example snippet you provide in this repo at
https://github.com/python-xlib/python-xlib/blob/master/examples/nvcontrol.py

The weird thing is, I get an ```AttributeError: nvcontrol_get_gpu_count``` if I try to call nvcontrol_get_gpu_count ; however in the list of extensions 
```
display.list_extensions())
```
I do find listed NV-CONTROL. Do you have  any insights on why that might happen?

I run Debian 10 on a 2 GPU machine with KDE plasma as desktop

**Comment by ga1i13o** [comment]
I am using a conda env with python 3.8

I actually found the issue. I had installed from pip ```python3-xlib```
Removing it and installing ```python-xlib``` made the snippet work

Hope this can be useful to someone

**Comment by vasily-v-ryabov** [comment]
Yes, `python3-xlib` is non-maintained fork.
