### ISSUE TITLE
Without display number in authorization: Can't connect to display, No protocol specified

### ISSUE THREAD

**Issue by podiki** [python-xlib/python-xlib#207]
Bug was reported here: https://bugs.launchpad.net/ubuntu/+source/python-xlib/+bug/1885304

Can confirm I see the same thing (on a Guix system, GDM, running just a WM), namely that `xauth list` shows shows an entry with `machinename/unix:` and no display number. This causes an application to fail to launch with the error that it "can't connect to display, no protocol specified."

Adding a display number with

```
xauth add $DISPLAY $(xauth list $DISPLAY | cut -d: -f2- | tail -1)
```

causes the error to go away and the Python program using python-xlib to launch. I have not tried the potential fixes in that bug report, but seems like an easy fix. See https://bugs.launchpad.net/ubuntu/+source/python-xlib/+bug/1885304/comments/3

(A workaround is to use a command to add authorization, like `xhost +SI:localuser:username`, which also will work.)

**Comment by podiki** [comment]
In my quick testing so far the proposed patch in https://bugs.launchpad.net/ubuntu/+source/python-xlib/+bug/1885304/comments/3 hasn't worked, but removing the `num == enum` matching entirely did. (Simply: I'm not familiar enough with python-xlib to know what it is reading in for `enum` when there is no display number in xauth.)

**Comment by Majiir** [comment]
I am also experiencing this issue on a NixOS 22.05 system with GDM and GNOME 42.2 on Xorg. To reproduce:

```sh
nix-shell -p python3Packages.xlib --run "python -c 'from Xlib.display import Display; Display()'"
```

With a slight modification (`b''` instead of `""`) to the patch described in [that comment](https://bugs.launchpad.net/ubuntu/+source/python-xlib/+bug/1885304/comments/3), the issue is fixed:

```diff
--- a/Xlib/xauth.py
+++ b/Xlib/xauth.py
@@ -120,6 +120,8 @@ class Xauthority(object):
         matches = {}
 
         for efam, eaddr, enum, ename, edata in self.entries:
+            if enum == b'' and ename not in matches:
+                enum = num
             if efam == family and eaddr == address and num == enum:
                 matches[ename] = edata
```
