### ISSUE TITLE
Some windows are not listed in Display().screen().root.query_tree().children

### ISSUE THREAD

**Issue by Amalvir** [python-xlib/python-xlib#211]
I am on Ubuntu 21.10 with Gnome Wayland and it appears that when I run a simple loop like that :
```python
for a in display.Display().screen().root.query_tree().children:
    print(a.get_full_text_property(Xatom.WM_NAME, Display().get_atom('STRING')))
```
or
```python
for a in display.Display().screen().root.query_tree().children:
    print(a.get_wm_name())
```
Some open windows like nautilus or Inkscape are missing. 
Moreover, when I close nautilus or Inkscape, there is still the same number of lines.

**Comment by Borisd93** [comment]
well i think that's because you're using wayland, and this library is for X11, maybe some windows are running on wayland and the others on x11

**Comment by Amalvir** [comment]
Yes, you are right because when I log in as Ubuntu Xorg, it works. So it is not an issue; it's just not compatible with Wayland.
