### ISSUE TITLE
Update the python-xlib homepage.

### ISSUE THREAD

**Issue by exhuma** [python-xlib/python-xlib#24]
The homepage does not mention anything about this github project. It maybe should as this seems to be the most active repository for python-xlib.

**Comment by vasily-v-ryabov** [comment]
Sure. Readme update + Sphinx-generated docs are on the TODO list. And we still didn't finish 2to3 fixes. About 3/4 of them have been done. My time to work on this project is very limited. Any help is welcome. Hope to make Py2/Py3 compatible release this summer (~July-August) because another project `pywinauto` will rely on `python-xlib` soon.

**Comment by petli** [comment]
I've updated http://python-xlib.sourceforge.net/ and https://sourceforge.net/projects/python-xlib/ to make it clear that the project now exists in this repository.

**Comment by mondeja** [comment]
The [example programs](http://python-xlib.sourceforge.net/?page=documentation) link on [documentation page](http://python-xlib.sourceforge.net/?page=documentation) is broken.

**Comment by exhuma** [comment]
@vasily-v-ryabov How are the pages on SF generated? Are their source documents in this gihub repo? That way people could make PRs to fix documentation issues. If you let me know where, I could take a look.

**Comment by petli** [comment]
Way back 2001 I just FTPd the files to SF, the way it was done then, so the files would have to be downloaded from there. I'd like dropping that last remnant of SF. Is a site needed at all beyond the README in the repo?

**Comment by exhuma** [comment]
A site gives you the opportunity to publish API docs, which is almost always useful. If only to evaluate the API without wading through the code.

Have you considered using [GitHub Pages](https://guides.github.com/features/pages/) instead? At least they would be open to pull-requests.

**Comment by vasily-v-ryabov** [comment]
Sorry, I have too little time and 2 more open source projects with higher priority but all are just a hobby. I've created empty GitHub Pages repo for python-xlib: https://github.com/python-xlib/python-xlib.github.io ([result page](https://python-xlib.github.io/)). Now it's open for pull requests.

**Comment by exhuma** [comment]
I know how that feels. I've got a bunch of projects myself as well, both open- and closed-source. Keeping up with issues and PRs can be time-consuming. But PRs help a lot. So thank you for doing this and hopefully this will take some work off your shoulders :smiley:

**Comment by thiagokokada** [comment]
I decided to generate the docs and open a PR: https://github.com/python-xlib/python-xlib.github.io/pull/1

**Comment by petli** [comment]
Wow, thanks!
