### ISSUE TITLE
Fix python2.7 -3 deprecation warnings

### ISSUE THREAD

**Issue by frafra** [python-xlib/python-xlib#4]
Current situation (initial import, commit d6a5a490805125f24c6a46ba765312252388626b):

```
$ (shopt -s globstar; for s in */**.py; do timeout 1 python2 -3 "$s"; done) 2>error.log
$ grep DeprecationWarning error.log | cut -f4- -d: | sort | uniq -c | sort -nr
    264  apply() not supported in 3.x; use func(*args, **kwargs)
    160  buffer() not supported in 3.x
     47  classic int division
     39  dict.has_key() not supported in 3.x; use the in operator
     24  The 'new' module has been removed in Python 3.0; use the 'types' module instead.
      5  CObject type is not supported in 3.x. Please use capsule objects instead.
      3  in 3.x, __getslice__ has been removed; use __getitem__
```

Every patch that lowers the number without causing regression is welcome :)

**Comment by frafra** [comment]
About `in 3.x, __getslice__ has been removed; use __getitem__`:
```
$ grep -Ir __getslice__ . | grep -v ^./error.log
./test/gen/genprottest.py:    def __getslice__(self, x, y):
./test/test_events_be.py:    def __getslice__(self, x, y):
./test/test_events_le.py:    def __getslice__(self, x, y):
./test/test_requests_be.py:    def __getslice__(self, x, y):
./test/test_requests_le.py:    def __getslice__(self, x, y):
./utils/parsexbug.py:    def __getslice__(self, i, j):
```

About `CObject type is not supported in 3.x. Please use capsule objects instead.`: it looks like an external issue.
```
$ grep -m1 CObject error.log
/usr/lib64/python2.7/site-packages/dbus/types.py:6: DeprecationWarning: CObject type is not supported in 3.x. Please use capsule objects instead.
$ grep -Ir _dbus_bindings . | grep -v ^./error.log || echo 'No matches'
No matches
```

About `The 'new' module has been removed in Python 3.0; use the 'types' module instead.`:
```
$ grep -Irl 'import new' . | grep -v ^./error.log
./Xlib/display.py
./Xlib/protocol/rq.py
./build/lib/Xlib/display.py
./build/lib/Xlib/protocol/rq.py
$ grep -Ir 'import new\|new\.' . | grep -v ^./error.log | wc -l
20
```
About `dict.has_key() not supported in 3.x; use the in operator`:
```
$ grep -Irl '.has_key\(\)' . | grep -v ^./error.log
./Xlib/display.py
./Xlib/protocol/rq.py
./Xlib/protocol/display.py
./Xlib/rdb.py
./build/lib/Xlib/display.py
./build/lib/Xlib/rdb.py
./build/lib/Xlib/protocol/rq.py
./build/lib/Xlib/protocol/display.py
$ grep -Ir '.has_key\(\)' . | grep -v ^./error.log | wc -l
28
```

About `classic int division`: it should be fine to replace "/" with "//" when used as mathematical operator.

`buffer()` could be ported using 2to3 with `-f buffer`.

`apply()` is probably the most boring one: http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#apply

**Comment by frafra** [comment]
I've created a separate branch for this:
https://github.com/python-xlib/python-xlib/tree/deprecationwarning-fixes

**Comment by vasily-v-ryabov** [comment]
Automated QuantifiedCode checks might be useful too: https://www.quantifiedcode.com/app/project/gh:python-xlib:python-xlib

**Comment by frafra** [comment]
Thank you @vasily-v-ryabov!

**Comment by vasily-v-ryabov** [comment]
I've made fixes for `new`. And many imports are relative now. Py3 tests are failing, but I've enabled them to indicate a progress. Travis CI shows the build as green, but if you dive into Py3.x jobs output there are many failed tests. But Py2 tests are 100% OK. See pull request #8.

**Comment by vasily-v-ryabov** [comment]
Only `buffer() not supported in 3.x` is left to fix from this list. Other Py3 test failures require more detailed investigation. Pull request #16 reduced the number of failures to `(failures=47, errors=5)`.

**Comment by vasily-v-ryabov** [comment]
@benoit-pierre has fixed the rest of deprecated things and Py3 failures. Closing.
