### ISSUE TITLE
python-xlib crashes app when $DISPLAY contains remote IP address

### ISSUE THREAD

**Issue by bennabiy** [python-xlib/python-xlib#53]
I discovered this issue when my mate-menu disappeared on remote terminals which forwarded their desktop across the network with simple X  (not through SSH). After debugging a bit, I managed to find this.

```python
user@compulab:~$ python -c 'from Xlib import display; d=display.Display()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 119, in new_get_auth
    return au.get_best_auth(family, addr, dno)
  File "/usr/lib/python2.7/dist-packages/Xlib/xauth.py", line 114, in get_best_auth
    address = address.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)
user@compulab:~$ 
```
where the 0xc0 corresponds to the first set of the IP address, 192.

The issue can be isolated to python-xlib by the command 
`$ python -c 'from Xlib import display; d=display.Display()'` from a remote display not over ssh.

**Comment by benoit-pierre** [comment]
What version are you using?

**Comment by bennabiy** [comment]
```
# apt-cache show python-xlib
Package: python-xlib
Priority: extra
Section: universe/python
Installed-Size: 740
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: all
Version: 0.14+20091101-5
Provides: python2.7-xlib
Depends: python:any (<< 2.8), python:any (>= 2.7.5-5~)
Filename: pool/universe/p/python-xlib/python-xlib_0.14+20091101-5_all.deb
Size: 101372
MD5sum: f2359eee468f01a79576681655f85c6f
SHA1: 684dd250fadb86024aa9130355e2a3293d27f6df
SHA256: c158bf1ac78c8ce9c602d57d34d7ebfeb01e1410af31327f258c305a39055da3
Description-en: interface for Python to the X11 protocol
 python-xlib is a 100% pure Python implementation of the X11
 protocol. It currently implements client-side X11R6 fully, supports
 the resource database, ICCM, and the Shape extension.
 .
 This is a Python 2 version of the package
Description-md5: 07871d2da4c702500862f163d9092247
Homepage: http://python-xlib.sourceforge.net/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 3y
Task: edubuntu-desktop-gnome, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-mate-cloudtop

```
And my $DISPLAY is `192.168.5.30:7`

**Comment by benoit-pierre** [comment]
Can you try with the latest release? You can find Ubuntu packages on my [PPA](https://launchpad.net/~benoit.pierre/+archive/ubuntu/plover).

**Comment by bennabiy** [comment]
As of latest release, the ascii error is gone, but still an error. `Traceback (most recent call last):
  File "/usr/lib/mate-menu/mate-menu.py", line 817, in applet_factory
    MenuWin( applet, iid )
  File "/usr/lib/mate-menu/mate-menu.py", line 485, in __init__
    self.keybinder = keybinding.GlobalKeyBinding()
  File "/usr/lib/python2.7/dist-packages/mate_menu/keybinding.py", line 62, in __init__
    self.display = Display()
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 136, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display "192.168.5.30:7": No protocol specified`

and with the python command above: `# python -c 'from Xlib import display; d=display.Display()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 136, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display "192.168.5.30:7.0": No protocol specified
`

**Comment by bennabiy** [comment]
It seems that it is hitting this bug... https://github.com/LiuLang/python3-xlib/pull/7/files

I tested by doing xhost +servername and then trying, and it worked fine. so I manually patched the file xauth.py and am trying it now.

**Comment by bennabiy** [comment]
Did not fix it. So far only thing that works is xhost +servername on the display host.

**Comment by bennabiy** [comment]
At best I can tell, when I run through pdb, it chokes because it cannot read the entry from .Xauthority properly, so if does not find an entry.

**Comment by benoit-pierre** [comment]
The problem is `bytes(int(x) for x in ('127', '0', '0', '1'))` return a bytestring with Python 3, but a generator with Python 2.

Can you try master with this patch please:
```diff
diff --git i/Xlib/support/unix_connect.py w/Xlib/support/unix_connect.py
index 5da3795..4add2db 100644
--- i/Xlib/support/unix_connect.py
+++ w/Xlib/support/unix_connect.py
@@ -109,7 +109,7 @@ def new_get_auth(sock, dname, host, dno):
         # Convert the prettyprinted IP number into 4-octet string.
         # Sometimes these modules are too damn smart...
         octets = sock.getpeername()[0].split('.')
-        addr = bytes(int(x) for x in octets)
+        addr = bytearray(int(x) for x in octets)
     else:
         family = xauth.FamilyLocal
         addr = socket.gethostname().encode()
```

**Comment by bennabiy** [comment]
Works beautifully (after I removed all my pdb.set_trace() calls ;)

**Comment by benoit-pierre** [comment]
Great, thank! I'll submit a PR.

**Comment by bennabiy** [comment]
Thank you @benoit-pierre for your attention to this. I was starting to get discouraged when seeing the lack of activity in #python-xlib channel on IRC.
