### ISSUE TITLE
Not getting events with next_event()

### ISSUE THREAD

**Issue by vga101** [python-xlib/python-xlib#63]
Reading of events such as mouse movement with Display.next_event() doesn't work for me. Is there anything recommended for debugging? Other functionality of python-xlib works. Getting the events with X11 command line tool as "xinput --test-xi2" also works fine as expected (prints events). This issue occurs both for the provided example file "examples/xinput.py" and a minimized version of it (see below).

Tested on Ubuntu 14.04 within a virtualenv with Python 2.7. I've tested with python-xlib release 0.17 installed via pip as well as current master branch from github.

Mimized snippet for reproducing:
```
from Xlib.display import Display
display = Display()
print "display:", display
print "version:", display.xinput_query_version()
print "pending events", display.pending_events()
print "now waiting for next event:", display.next_event()
print "done."
```
which prints:
> display: <Xlib.display.Display object at 0x7fa417102910>
> version: <<class 'Xlib.ext.xinput.XIQueryVersion'> serial = 13, data = {'major_version': 2, 'sequence_number': 13, 'minor_version': 0}, error = None>
> pending events 0

and then hangs with the next_event() call despite mouse motion.

Any help or comments appreciated - thanks.

**Comment by benoit-pierre** [comment]
You're missing a call to `xinput_select_events` to select which event(s) to monitor, and on what device(s). Example to monitor all mouse events for all devices on the root window (`example/xinput.py` monitor hierarchy changes, not mouse events):
```
display.screen().root.xinput_select_events([(xinput.AllDevices,
                                             xinput.ButtonPressMask |
                                             xinput.ButtonReleaseMask |
                                             xinput.EnterMask)])
```

**Comment by vga101** [comment]
Oh, sounds reasonable. ;-)
Works now (using Xlib.X.PointerMotionMask actually). Thanks a lot!

**Comment by vga101** [comment]
Does python-xlib also support getting XI2 events (as in "xinput --test-xi2"), which give also relative pointer motion outside the screen boundaries? Couldn't find these events mentioned in the documentation at http://python-xlib.sourceforge.net/doc/html/python-xlib_12.html.

**Comment by benoit-pierre** [comment]
I meant to use `Xlib.ext.xinput.MotionMask`, that's what you should use (even if it does happen to work with `Xlib.X.PointerMotionMask` because its value is the same).

As for you're question, I'd look at the source for `xinput --test-xi2`, and translate that to Python. But do note that not all of Xinput is supported.

**Comment by vga101** [comment]
I couldn't find support for XI2 xlib cookie events in python-xlib, so I'm now getting the relative pointer motion events externally through the C API as done by `xinput --test-xi2`. Thanks a lot for your help.
