### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Ofekmeister** [python-xlib/python-xlib#7]
Hello! I read the mailing list on SF. Is this going to support Python 3.3+ now? (3.3 is the real start of 3.x btw) If so, how can one help? What needs to be done?

**Comment by vasily-v-ryabov** [comment]
Hi @Ofekmeister , we're fixing deprecated old statements first (see issue #4 for details). The process is not very fast, so any help is welcome. Feel free to send pull requests to the master branch. It's also easy to enable Py3.3 ... Py3.5 in `.travis.yml` when the tests are OK.

**Comment by Ofekmeister** [comment]
To be clear... may I make backwards incompatible changes or are we supporting py2 for a time?

**Comment by petli** [comment]
The library should support both Python 2 and 3, in my opinion.

**Comment by vasily-v-ryabov** [comment]
Agree, I'd prefer Py 2.6/2.7 support too.

**Comment by vasily-v-ryabov** [comment]
Closing this since 0.16 is out.
