### ISSUE TITLE
Grabbing a key does not stop propagation of event

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [python-xlib/python-xlib#79]
As the title says. I'm not entirely clear on `owner_events`, but both True and False behave the same.
Tested on ubuntu 16.10.
It partially works on ubuntu 14.04, by partially I mean grabbing a modified key (e.g.`<super><shift>p`) works as expected, but grabbing a key without modifiers does not stop event propagation.

**Comment by benoit-pierre** [comment]
It's kinda hard to help without more information on what it is you're trying to do exactly and/or access to your code.

**Comment by OzymandiasTheGreat** [comment]
I'm terribly sorry, I forgot numlock is considered a modifier.
Grabbing an unmodified key still doesn't work, after upgrading to python-xlib 0.19 it now gives an error:
`X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 706, sequence_number = 13, major_opcode = 33, minor_opcode = 0`
Here's the code, it's a small snippet so I'm putting it here:
```from Xlib import display, X, XK
local_display = display.Display()
root = local_display.screen().root
keycode = local_display.keysym_to_keycode(XK.XK_Tab)
root.grab_key(keycode, X.AnyModifier, False, X.GrabModeAsync, X.GrabModeAsync)
while True:
    event = root.display.next_event()
    if event.type == X.KeyPress:
        print('Key pressed')
```

**Comment by benoit-pierre** [comment]
It's possible that another program (like your window manager) is already grabbing a combination of tab+modifier(s), in which case the call will fail, as [documented](https://manpages.debian.org/jessie/libx11-doc/XGrabKey.3.en.html):
```
If some other client has issued a XGrabKey with the same key combination on the same window, a BadAccess error results.  When using AnyModifier or AnyKey, the request fails completely, and a BadAccess error results (no grabs are established) if there is a conflicting grab for any combination.
```

Try something along those lines instead:
```python
from Xlib import X, display

display = display.Display()
screen = display.screen()
grab_window = screen.root

for keycode in (38, 39, 40, 41): # asdf
    grab_window.grab_key(keycode, 0, False, X.GrabModeAsync, X.GrabModeAsync)
    # Grab keycode+numlock combo too.
    grab_window.grab_key(keycode, X.Mod2Mask, False, X.GrabModeAsync, X.GrabModeAsync)

while True:
    event = display.next_event()
    print(event)

**Comment by OzymandiasTheGreat** [comment]
And yup, that works. I feel silly for missing that bit. Thanks.
