### ISSUE TITLE
Which methods return the x,y coordinate of any application or window? 

### ISSUE THREAD

**Issue by WalterWangNYUMLC** [python-xlib/python-xlib#81]
I am trying to get the x,y position of an application using the xlib library. However, methods like get_geometry() only return 0,0 for location of the application. Not sure which function or atom to use. Any help?

**Comment by benoit-pierre** [comment]
Try `win.translate_coords(disp.screen().root, 0, 0)`.

**Comment by WalterWangNYUMLC** [comment]
ty, it worked!
