### ISSUE TITLE
`send_and_recv` performance issue

### ISSUE THREAD

**Issue by cykerway** [python-xlib/python-xlib#86]
https://github.com/python-xlib/python-xlib/blob/63d5cf15901ec945ac45c6a58b58d12b491e5a9b/Xlib/protocol/display.py#L593

This simple program takes 10+ secs to run:

    from Xlib import display, X

    def main():
        win = display.Display().screen().root
        win.get_image(0, 0, 1280, 720, X.ZPixmap, 0xffffffff)

    for i in range(10):
        main()

Consider using a large recv buffer as it will drastically increase performance. For example, if you use 2M instead of 2K buffer then the same program can have 20x speed boost.

Commit here: https://github.com/cykerway/python-xlib/commit/a863c97a4a1f8c5d90514c1e128eeba6aa160615

**Comment by benoit-pierre** [comment]
How about this instead:
```diff
 Xlib/protocol/display.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git i/Xlib/protocol/display.py w/Xlib/protocol/display.py
index 61d4c8f..4329ffe 100644
--- i/Xlib/protocol/display.py
+++ w/Xlib/protocol/display.py
@@ -590,7 +590,8 @@ class Display(object):
                 # We're the recieving thread, parse the data
                 if recieving:
                     try:
-                        bytes_recv = self.socket.recv(2048)
+                        expected = self.recv_packet_len - len(self.data_recv)
+                        bytes_recv = self.socket.recv(max(2048, expected))
                     except socket.error as err:
                         self.close_internal('server: %s' % err[1])
                         raise self.socket_error
```
This will take into account the size of the current response.

**Comment by cykerway** [comment]
Taking expected data length into account looks better than using a fixed value. Not sure why there's a lower cap but not an upper one, though. Is it possible that there will be a lot of data getting transferred?

On the other hand, if expected data length is known ahead, why would we need to max it against 2048 (even though it seems harmless)?

**Comment by benoit-pierre** [comment]
We don't know how much data is expected beforehand.  `self.recv_packet_len` is only valid (non-zero) if we have received the response header.
