### ISSUE TITLE
How to handle events with asyncio?

### ISSUE THREAD

**Issue by kootenpv** [python-xlib/python-xlib#94]
I'd like to integrate this with an existing asyncio loop. How can I make sure it works well with `disp.next_event()`?

**Comment by benoit-pierre** [comment]
I have never used `asyncio`, but maybe watch the display file descriptor? Something similar to [this code](https://github.com/openstenoproject/plover/blob/master/plover/oslayer/xkeyboardcontrol.py#L202).
